### PR TITLE
Fix TravisCI cross-build

### PR DESCRIPTION
**Pull request by dwijnand**
Thanks to @xuwei-k for [pointing it out](https://github.com/scala/scala-abide/pull/79/files/8efa132e7ed3fa7f56b28fb4219d37e64210ead9#r88389137).

### CODE REVIEW

**Comment by dwijnand** [comment]
Good thing I was working in the sbt/zinc codebase today.

TIL about sbt-doge's `plz`/`+++`: https://github.com/sbt/sbt-doge#strict-aggregation

(On the other hand I wrote sbt-abide instead of scala-abide about 20 times)

**Comment by SethTisue** [comment]
I'm not familiar with sbt-doge. Should I just go ahead and merge?

**Comment by dwijnand** [comment]
Yep, it's good.

Previously it was doing:
1. test the sbt plugin using scala 2.10.6 and everything else on 2.11.8, on openjdk6
2. test the sbt plugin using scala 2.10.6 and everything else on 2.11.8, on oraclejdk8

ie. +/- the same thing twice.

Now it does 3 parallel runs:
* the sbt plugin on 2.10.6 and openjdk6
* everything else on 2.11.8/openjdk6
* everything else on 2.12.0/oraclejdk8

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
