### PR TITLE
add LICENSE

### PR DESCRIPTION
**Pull request by SethTisue**
review by @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
@samarion @Lewix @dragos @rtfpessoa @andrewconner @stuhood are you okay with using the BSD-3 License, as does Scala? I guess this one was implied since it's the "Scala License", but I'd appreciate it if you could give your approval (or agree on another suitable license).

**Comment by adriaanm** [comment]
Also, we probably need to get a CLA process in place as in scala/scala.

**Comment by samarion** [comment]
BSD-3 sounds good to me.

**Comment by Lewix** [comment]
I'm fine with BSD-3 too.

**Comment by dragos** [comment]
👍

**Comment by SethTisue** [comment]
@rtfpessoa @andrewconner @stuhood ping

**Comment by rtfpessoa** [comment]
Sorry, I missed this. I'm also fine with BSD-3. 👍

**Comment by stuhood** [comment]
Fine by me.

**Comment by SethTisue** [comment]
@andrewconner ping

**Comment by SethTisue** [comment]
(I sent Andrew a private email about it.)

**Comment by andrewconner** [comment]
Sorry for the super slow reply — haven't been on GitHub in a month or so. Sounds great. 👍

**Comment by SethTisue** [comment]
thanks all! (and, I opened #77 on the need for CLA checking.)

**Pull request merged**
