### PR TITLE
misc upgrades and tweaks

### PR DESCRIPTION
**Pull request by SethTisue**
review by @adriaanm

### CODE REVIEW

**Comment by SethTisue** [comment]
some of this is more or less gratuitous, but the ScalaTest version bump and the `.sbtopts` parts are actually necessary.

**Comment by dwijnand** [comment]
Just out of curiosity, because it's not the first time I've seen it recently: is there a reason that `.sbtopts` is being used over `.jvmopts`? (https://github.com/paulp/sbt-extras#sbt--h)

**Comment by SethTisue** [comment]
I tried `.jvmopts` first and it didn’t work, I think because I’m using the launch script `brew install sbt` gives me

**Comment by dwijnand** [comment]
Ok. That makes sense. (But is also a terrible state of affairs). Thanks.

**Comment by dragos** [comment]
LGTM

**Pull request merged**
