### PR TITLE
Replace scalariform plugin

### PR DESCRIPTION
**Pull request by wslulciuc**
This PR introduces the [`scalariform`](https://github.com/sbt/sbt-scalariform) sbt plugin officially maintained / worked on at [`sbt/sbt-scalariform`](https://github.com/scala-ide).

### CODE REVIEW

**Comment by dragos** [comment]
LGTM

**Comment by wslulciuc** [comment]
@dragos adding newline char to `plugins.sbt` unintentionally pulled in `.gitignore` changes (updated comments to reflect that).

**Comment by dwijnand** [comment]
Tool specific ignores should be handed by the user's global gitginore.

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by wslulciuc** [comment]
@dwijnand reverted tool specific ignores.

**Comment by SethTisue** [comment]
thanks!

**Pull request merged**
